#!/bin/bash
# Remove all images that are older than an hour "until=1h"
docker image prune -a --force --filter "until=1h" > /dev/null 2> /dev/null < /dev/null

# Stop and remove old containers
docker stop goodreads-backend > /dev/null 2> /dev/null < /dev/null
docker rm goodreads-backend > /dev/null 2> /dev/null < /dev/null

aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 485380287493.dkr.ecr.ap-southeast-1.amazonaws.com > /dev/null 2> /dev/null < /dev/null

# Pull new image and run the container
docker pull 485380287493.dkr.ecr.ap-southeast-1.amazonaws.com/goodreads-backend:latest > /dev/null 2> /dev/null < /dev/null
docker run -d -p 9003:8080 --name goodreads-backend -v /mnt/efs/fs1:/tmp/efs/fs1 485380287493.dkr.ecr.ap-southeast-1.amazonaws.com/goodreads-backend:latest > /dev/null 2> /dev/null < /dev/null